routes/web.php
<?php

use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('test1');
});

Route::get('/tests/test1', [TestController::class, 'test1'])->name('test1');
Route::get('/tests/test2', [TestController::class, 'test2'])->name('test2');

Route::resource('karyawan', KaryawanController::class)->except('show');
Route::resource('jabatan', JabatanController::class)->except('show');
Route::resource('levels', LevelController::class)->except('show');
Route::resource('departments', DepartmentController::class)->except('show');

app/Models/Jabatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    use HasFactory;

    protected $table = 'jabatan';

    protected $primaryKey = 'id_jabatan';

    protected $fillable = [
        'nama_jabatan',
        'id_level',
    ];

    public $timestamps = false;

    public function level()
    {
        return $this->belongsTo(Level::class, 'id_level', 'id_level');
    }

    public function karyawans()
    {
        return $this->hasMany(Karyawan::class, 'id_jabatan', 'id_jabatan');
    }
}

app/Http/Controllers/Api/JabatanController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Jabatan\StoreJabatanRequest;
use App\Http\Requests\Jabatan\UpdateJabatanRequest;
use App\Http\Resources\Jabatan\JabatanResource;
use App\Models\Jabatan;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $jabatan = Jabatan::all();

        return response()->success(Response::HTTP_OK, null, JabatanResource::collection($jabatan));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreJabatanRequest $request)
    {
        $validated = $request->validated();

        $jabatan = Jabatan::create($validated);

        return response()->success(Response::HTTP_CREATED, 'Jabatan created successfully.', [
            'id_jabatan' => $jabatan->id_jabatan,
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $jabatan = Jabatan::findOrFail($id);

        return response()->success(Response::HTTP_OK, null, $jabatan);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateJabatanRequest $request, string $id)
    {
        $validated = $request->validated();

        $jabatan = Jabatan::findOrFail($id);
        $jabatan->update($validated);

        return response()->success(Response::HTTP_OK, 'Jabatan updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $jabatan = Jabatan::findOrFail($id);

        $jabatan->delete();

        return response()->success(Response::HTTP_OK, 'Jabatan deleted successfully.');
    }
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('pages.jabatan.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.jabatan.create');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        return view('pages.jabatan.edit', compact('id'));
    }
}

resources/views/pages/jabatan/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Jabatan')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Tambah Jabatan</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="jabatan" action="{{ route('api.jabatan.store') }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama_jabatan" name="nama_jabatan"
                                    placeholder="Masukan Nama Jabatan">
                                <small id="invalid-nama_jabatan" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <select class="form-select" id="id_level" name="id_level">
                                </select>
                                <small id="invalid-id_level" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('jabatan.index') }}" class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.levels.index') !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    data.forEach(element => {
                        $('#id_level').append(new Option(element.nama_level, element
                            .id_level));
                    });
                }
            });

            $('#jabatan').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#jabatan').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('jabatan.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/jabatan/edit.blade.php
@extends('layouts.app')

@section('title', 'Ubah Jabatan')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Ubah Jabatan</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="jabatan" action="{{ route('api.jabatan.update', $id) }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama_jabatan" name="nama_jabatan"
                                    placeholder="Masukan Nama Jabatan">
                                <small id="invalid-nama_jabatan" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <select class="form-select" id="id_level" name="id_level">
                                </select>
                                <small id="invalid-id_level" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('jabatan.index') }}" class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.levels.index') !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    data.forEach(element => {
                        $('#id_level').append(new Option(element.nama_level, element
                            .id_level));
                    });
                }
            });

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.jabatan.show', $id) !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    $('#nama_jabatan').val(data.nama_jabatan);
                    setTimeout(function() {
                        $('#id_level').val(data.id_level).change();
                    }, 200);
                }
            });

            $('#jabatan').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'PUT',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#jabatan').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('jabatan.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/jabatan/index.blade.php
@extends('layouts.app')

@section('title', 'Jabatan')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-10">
            <a href="{{ route('jabatan.create') }}" class="btn btn-primary mb-2">Tambah Jabatan</a>
            <div class="table-responsive">
                <table id="jabatan" class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nama Jabatan</th>
                            <th>Level</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            let _datatable;
            let dt_init = $('#jabatan');

            _datatable = dt_init.DataTable({
                ajax: {
                    url: '{!! route('api.jabatan.index') !!}',
                    dataSrc: 'data',
                },
                columns: [{
                        'data': 'nama_jabatan',
                    },
                    {
                        'data': 'nama_level',
                    },
                    {
                        'data': null,
                        'render': function(data) {
                            const id = data.id_jabatan;

                            let urlEdit = "{{ route('jabatan.edit', ':id_jabatan') }}"
                            urlEdit = urlEdit.replace(':id_jabatan', id);
                            let urlDelete = "{{ route('api.jabatan.destroy', ':id_jabatan') }}"
                            urlDelete = urlDelete.replace(':id_jabatan', id);

                            return '<div class="d-flex justify-content-start"><a href="' +
                                urlEdit +
                                '" class="btn btn-warning text-white me-2">Ubah</a><a href="' +
                                urlDelete +
                                '" onclick="return confirm(\'Apakah anda yakin? \')" class="btn btn-danger text-white btn-delete">Hapus</a></div>';
                        }
                    },
                ],
                columnDefs: [{
                    orderable: false,
                    searchable: false,
                    targets: 2
                }],
            });

            dt_init.delegate('a.btn-delete', 'click', function(e) {
                e.preventDefault();

                const url = $(this).attr('href');

                $.ajax({
                    method: 'DELETE',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: url,
                    success: function(response) {
                        alert(response.message);
                        window.location.href = "{{ route('jabatan.index') }}";
                    }
                });
            });
        });
    </script>
@endpush