routes/web.php
<?php

use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('test1');
});

Route::get('/tests/test1', [TestController::class, 'test1'])->name('test1');
Route::get('/tests/test2', [TestController::class, 'test2'])->name('test2');

Route::resource('karyawan', KaryawanController::class)->except('show');
Route::resource('jabatan', JabatanController::class)->except('show');
Route::resource('levels', LevelController::class)->except('show');
Route::resource('departments', DepartmentController::class)->except('show');

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;

    protected $table = 'department';

    protected $primaryKey = 'id_dept';

    protected $fillable = [
        'nama_dept',
    ];

    public $timestamps = false;

    public function karyawans()
    {
        return $this->hasMany(Karyawan::class, 'id_dept', 'id_dept');
    }
}

app/Http/Controllers/Api/DepartmentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Department\StoreDepartmentRequest;
use App\Http\Requests\Department\UpdateDepartmentRequest;
use App\Models\Department;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $departments = Department::all();

        return response()->success(Response::HTTP_OK, null, $departments);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreDepartmentRequest $request)
    {
        $validated = $request->validated();

        $department = Department::create($validated);

        return response()->success(Response::HTTP_CREATED, 'Department created successfully.', [
            'id_dept' => $department->id_dept,
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $department = Department::findOrFail($id);

        return response()->success(Response::HTTP_OK, null, $department);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateDepartmentRequest $request, string $id)
    {
        $validated = $request->validated();

        $department = Department::findOrFail($id);
        $department->update($validated);

        return response()->success(Response::HTTP_OK, 'Department updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $department = Department::findOrFail($id);

        $department->delete();

        return response()->success(Response::HTTP_OK, 'Department deleted successfully.');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('pages.department.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.department.create');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        return view('pages.department.edit', compact('id'));
    }
}

resources/views/pages/department/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Department')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Tambah Department</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="department" action="{{ route('api.departments.store') }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama_dept" name="nama_dept"
                                    placeholder="Masukan Nama Level">
                                <small id="invalid-nama_dept" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('departments.index') }}"
                                    class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            $('#department').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#department').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('departments.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/department/edit.blade.php
@extends('layouts.app')

@section('title', 'Ubah Department')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Ubah Department</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="department" action="{{ route('api.departments.update', $id) }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama_dept" name="nama_dept"
                                    placeholder="Masukan Nama Level">
                                <small id="invalid-nama_dept" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('departments.index') }}"
                                    class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.departments.show', $id) !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    $('#nama_dept').val(data.nama_dept);
                }
            });

            $('#department').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'PUT',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#department').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('departments.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/department/index.blade.php
@extends('layouts.app')

@section('title', 'Department')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-10">
            <a href="{{ route('departments.create') }}" class="btn btn-primary mb-2">Tambah Department</a>
            <div class="table-responsive">
                <table id="department" class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nama Department</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            let _datatable;
            let dt_init = $('#department');

            _datatable = dt_init.DataTable({
                ajax: {
                    url: '{!! route('api.departments.index') !!}',
                    dataSrc: 'data',
                },
                columns: [{
                        'data': 'nama_dept',
                    },
                    {
                        'data': null,
                        'render': function(data) {
                            const id = data.id_dept;

                            let urlEdit = "{{ route('departments.edit', ':id_dept') }}"
                            urlEdit = urlEdit.replace(':id_dept', id);
                            let urlDelete = "{{ route('api.departments.destroy', ':id_dept') }}"
                            urlDelete = urlDelete.replace(':id_dept', id);

                            return '<div class="d-flex justify-content-start"><a href="' +
                                urlEdit +
                                '" class="btn btn-warning text-white me-2">Ubah</a><a href="' +
                                urlDelete +
                                '" onclick="return confirm(\'Apakah anda yakin? \')" class="btn btn-danger text-white btn-delete">Hapus</a></div>';
                        }
                    },
                ],
                columnDefs: [{
                    orderable: false,
                    searchable: false,
                    targets: 1
                }],
            });

            dt_init.delegate('a.btn-delete', 'click', function(e) {
                e.preventDefault();

                const url = $(this).attr('href');

                $.ajax({
                    method: 'DELETE',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: url,
                    success: function(response) {
                        alert(response.message);
                        window.location.href = "{{ route('departments.index') }}";
                    }
                });
            });
        });
    </script>
@endpush