routes/web.php
<?php

use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('test1');
});

Route::get('/tests/test1', [TestController::class, 'test1'])->name('test1');
Route::get('/tests/test2', [TestController::class, 'test2'])->name('test2');

Route::resource('karyawan', KaryawanController::class)->except('show');
Route::resource('jabatan', JabatanController::class)->except('show');
Route::resource('levels', LevelController::class)->except('show');
Route::resource('departments', DepartmentController::class)->except('show');

app/Models/Level.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    use HasFactory;

    protected $table = 'level';

    protected $primaryKey = 'id_level';

    protected $fillable = [
        'nama_level',
    ];

    public $timestamps = false;

    public function jabatans()
    {
        return $this->hasMany(Jabatan::class, 'id_level', 'id_level');
    }
}

app/Http/Controllers/Api/LevelController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Level\StoreLevelRequest;
use App\Http\Requests\Level\UpdateLevelRequest;
use App\Models\Level;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class LevelController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $levels = Level::all();

        return response()->success(Response::HTTP_OK, null, $levels);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreLevelRequest $request)
    {
        $validated = $request->validated();

        $level = Level::create($validated);

        return response()->success(Response::HTTP_CREATED, 'Level created successfully.', [
            'id_level' => $level->id_level,
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $level = Level::findOrFail($id);

        return response()->success(Response::HTTP_OK, null, $level);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateLevelRequest $request, string $id)
    {
        $validated = $request->validated();

        $level = Level::findOrFail($id);
        $level->update($validated);

        return response()->success(Response::HTTP_OK, 'Level updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $level = Level::findOrFail($id);

        $level->delete();

        return response()->success(Response::HTTP_OK, 'Level deleted successfully.');
    }
}

app/Http/Controllers/LevelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LevelController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('pages.level.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.level.create');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        return view('pages.level.edit', compact('id'));
    }
}

resources/views/pages/level/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Level')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Tambah Level</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="level" action="{{ route('api.levels.store') }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama_level" name="nama_level"
                                    placeholder="Masukan Nama Level">
                                <small id="invalid-nama_level" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('levels.index') }}" class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            $('#level').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#level').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('levels.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/level/edit.blade.php
@extends('layouts.app')

@section('title', 'Tambah Level')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Tambah Level</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="level" action="{{ route('api.levels.update', $id) }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama_level" name="nama_level"
                                    placeholder="Masukan Nama Level">
                                <small id="invalid-nama_level" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('levels.index') }}" class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.levels.show', $id) !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    $('#nama_level').val(data.nama_level);
                }
            });

            $('#level').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'PUT',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#level').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('levels.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/level/index.blade.php
@extends('layouts.app')

@section('title', 'Level')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-10">
            <a href="{{ route('levels.create') }}" class="btn btn-primary mb-2">Tambah Level</a>
            <div class="table-responsive">
                <table id="level" class="table table-hover">
                    <thead>
                        <tr>
                            <th>Nama Level</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            let _datatable;
            let dt_init = $('#level');

            _datatable = dt_init.DataTable({
                ajax: {
                    url: '{!! route('api.levels.index') !!}',
                    dataSrc: 'data',
                },
                columns: [{
                        'data': 'nama_level',
                    },
                    {
                        'data': null,
                        'render': function(data) {
                            const id = data.id_level;

                            let urlEdit = "{{ route('levels.edit', ':id_level') }}"
                            urlEdit = urlEdit.replace(':id_level', id);
                            let urlDelete = "{{ route('api.levels.destroy', ':id_level') }}"
                            urlDelete = urlDelete.replace(':id_level', id);

                            return '<div class="d-flex justify-content-start"><a href="' +
                                urlEdit +
                                '" class="btn btn-warning text-white me-2">Ubah</a><a href="' +
                                urlDelete +
                                '" onclick="return confirm(\'Apakah anda yakin? \')" class="btn btn-danger text-white btn-delete">Hapus</a></div>';
                        }
                    },
                ],
                columnDefs: [{
                    orderable: false,
                    searchable: false,
                    targets: 1
                }],
            });

            dt_init.delegate('a.btn-delete', 'click', function(e) {
                e.preventDefault();

                const url = $(this).attr('href');

                $.ajax({
                    method: 'DELETE',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: url,
                    success: function(response) {
                        alert(response.message);
                        window.location.href = "{{ route('levels.index') }}";
                    }
                });
            });
        });
    </script>
@endpush