routes/web.php
<?php

use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\KaryawanController;
use App\Http\Controllers\LevelController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect()->route('test1');
});

Route::get('/tests/test1', [TestController::class, 'test1'])->name('test1');
Route::get('/tests/test2', [TestController::class, 'test2'])->name('test2');

Route::resource('karyawan', KaryawanController::class)->except('show');
Route::resource('jabatan', JabatanController::class)->except('show');
Route::resource('levels', LevelController::class)->except('show');
Route::resource('departments', DepartmentController::class)->except('show');

app/Models/Karyawan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Karyawan extends Model
{
    use HasFactory;

    protected $table = 'karyawan';

    protected $primaryKey = 'id_karyawan';

    protected $fillable = [
        'nik',
        'nama',
        'ttl',
        'alamat',
        'id_jabatan',
        'id_dept',
    ];

    public $timestamps = false;

    public function jabatan()
    {
        return $this->belongsTo(Jabatan::class, 'id_jabatan', 'id_jabatan');
    }

    public function department()
    {
        return $this->belongsTo(Department::class, 'id_dept', 'id_dept');
    }
}

app/Http/Controllers/Api/KaryawanController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Karyawan\StoreKaryawanRequest;
use App\Http\Requests\Karyawan\UpdateKaryawanRequest;
use App\Http\Resources\Karyawan\KaryawanResource;
use App\Models\Karyawan;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class KaryawanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $karyawan = Karyawan::all();

        return response()->success(Response::HTTP_OK, null, KaryawanResource::collection($karyawan));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreKaryawanRequest $request)
    {
        $validated = $request->validated();

        $karyawan = Karyawan::create($validated);

        return response()->success(Response::HTTP_CREATED, 'Karyawan created successfully.', [
            'id_karyawan' => $karyawan->id_karyawan,
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $karyawan = Karyawan::findOrFail($id);

        return response()->success(Response::HTTP_OK, null, $karyawan);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateKaryawanRequest $request, string $id)
    {
        $validated = $request->validated();

        $karyawan = Karyawan::findOrFail($id);
        $karyawan->update($validated);

        return response()->success(Response::HTTP_OK, 'Karyawan updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $karyawan = Karyawan::findOrFail($id);

        $karyawan->delete();

        return response()->success(Response::HTTP_OK, 'Karyawan deleted successfully.');
    }
}

app/Http/Controllers/KaryawanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class KaryawanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('pages.karyawan.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pages.karyawan.create');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        return view('pages.karyawan.edit', compact('id'));
    }
}

resources/views/pages/karyawan/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Karyawan')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Tambah Karyawan</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="karyawan" action="{{ route('api.karyawan.store') }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nik" name="nik"
                                    placeholder="Masukan NIK Anda">
                                <small id="invalid-nik" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama" name="nama"
                                    placeholder="Masukan Nama Anda">
                                <small id="invalid-nama" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <input type="date" class="form-control" id="ttl" name="ttl">
                                <small id="invalid-ttl" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <textarea name="alamat" id="alamat" rows="5" class="form-control" placeholder="Masukan Alamat Anda"></textarea>
                                <small id="invalid-date" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <select class="form-select" id="id_jabatan" name="id_jabatan">
                                </select>
                                <small id="invalid-id_jabatan" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <select class="form-select" id="id_dept" name="id_dept">
                                </select>
                                <small id="invalid-id_dept" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('karyawan.index') }}" class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.jabatan.index') !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    data.forEach(element => {
                        $('#id_jabatan').append(new Option(element.nama_jabatan, element
                            .id_jabatan));
                    });
                }
            });

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.departments.index') !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    data.forEach(element => {
                        $('#id_dept').append(new Option(element.nama_dept, element
                            .id_dept));
                    });
                }
            });

            $('#karyawan').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'POST',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#karyawan').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('karyawan.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/karyawan/edit.blade.php
@extends('layouts.app')

@section('title', 'Ubah Karyawan')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card p-3">
                    <div class="row">
                        <h2 class="mb-3">Ubah Karyawan</h2>
                        <div id="liveAlertPlaceholder"></div>
                        <form id="karyawan" action="{{ route('api.karyawan.update', $id) }}" method="post">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nik" name="nik"
                                    placeholder="Masukan NIK Anda">
                                <small id="invalid-nik" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <input type="text" class="form-control" id="nama" name="nama"
                                    placeholder="Masukan Nama Anda">
                                <small id="invalid-nama" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <input type="date" class="form-control" id="ttl" name="ttl">
                                <small id="invalid-ttl" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <textarea name="alamat" id="alamat" rows="5" class="form-control" placeholder="Masukan Alamat Anda"></textarea>
                                <small id="invalid-date" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <select class="form-select" id="id_jabatan" name="id_jabatan">
                                </select>
                                <small id="invalid-id_jabatan" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="mb-3">
                                <select class="form-select" id="id_dept" name="id_dept">
                                </select>
                                <small id="invalid-id_dept" class="invalid text-danger">
                                </small>
                            </div>
                            <div class="d-flex justify-content-end">
                                <a href="{{ route('karyawan.index') }}" class="btn btn-outline-secondary me-2">Kembali</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        window.onload = function() {

        }

        $(document).ready(function() {
            'use strict';

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.departments.index') !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    data.forEach(element => {
                        $('#id_dept').append(new Option(element.nama_dept, element
                            .id_dept));
                    });
                }
            });

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.jabatan.index') !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    data.forEach(element => {
                        $('#id_jabatan').append(new Option(element.nama_jabatan, element
                            .id_jabatan));
                    });
                }
            });

            $.ajax({
                method: 'GET',
                headers: {
                    'Accept': 'application/json',
                },
                url: "{!! route('api.karyawan.show', $id) !!}",
                success: function(response) {
                    const {
                        data
                    } = response;

                    $('#nik').val(data.nik);
                    $('#nama').val(data.nama);
                    $('#ttl').val(data.ttl);
                    $('#alamat').val(data.alamat);
                    setTimeout(function() {
                        $('#id_jabatan').val(data.id_jabatan).change();
                        $('#id_dept').val(data.id_dept).change();
                    }, 200);
                }
            });

            $('#karyawan').on('submit', function(e) {
                e.preventDefault();

                const data = new FormData(e.target);
                const value = Object.fromEntries(data.entries());
                const alertPlaceholder = $('#liveAlertPlaceholder');

                $.ajax({
                    method: 'PUT',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: $('#karyawan').attr('action'),
                    data: value,
                    success: function(data) {
                        window.location.href = "{{ route('karyawan.index') }}";
                        alertPlaceholder.html('');
                        $('.invalid').html('');
                    },
                    error: function(error) {
                        const response = error.responseJSON;

                        const alert = [
                            `<div class="alert alert-danger alert-dismissible" role="alert">`,
                            `   <div>${response.message}</div>`,
                            '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                            '</div>'
                        ].join('');

                        alertPlaceholder.html(alert);

                        if ('error' in response) {
                            const {
                                error
                            } = response;

                            for (const key in error) {
                                $(`#invalid-${key}`).html(error[key][0]);
                            }
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/karyawan/index.blade.php
@extends('layouts.app')

@section('title', 'Karyawan')

@section('content')
    <div class="row d-flex justify-content-center mt-4">
        <div class="col-md-10">
            <a href="{{ route('karyawan.create') }}" class="btn btn-primary mb-2">Tambah Karyawan</a>
            <div class="table-responsive">
                <table id="karyawan" class="table table-hover">
                    <thead>
                        <tr>
                            <th>NIK</th>
                            <th>Nama</th>
                            <th>Tanggal Lahir</th>
                            <th>Alamat</th>
                            <th>Jabatan</th>
                            <th>Department</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('after-script')
    <script type="text/javascript">
        $(document).ready(function() {
            'use strict';

            let _datatable;
            let dt_init = $('#karyawan');

            _datatable = dt_init.DataTable({
                ajax: {
                    url: '{!! route('api.karyawan.index') !!}',
                    dataSrc: 'data',
                },
                columns: [{
                        'data': 'nik',
                    },
                    {
                        'data': 'nama',
                    },
                    {
                        'data': 'ttl',
                    },
                    {
                        'data': 'alamat',
                    },
                    {
                        'data': 'nama_jabatan',
                    },
                    {
                        'data': 'nama_dept',
                    },
                    {
                        'data': null,
                        'render': function(data) {
                            const id = data.id_karyawan;

                            let urlEdit = "{{ route('karyawan.edit', ':id_karyawan') }}"
                            urlEdit = urlEdit.replace(':id_karyawan', id);
                            let urlDelete = "{{ route('api.karyawan.destroy', ':id_karyawan') }}"
                            urlDelete = urlDelete.replace(':id_karyawan', id);

                            return '<div class="d-flex justify-content-start"><a href="' +
                                urlEdit +
                                '" class="btn btn-warning text-white me-2">Ubah</a><a href="' +
                                urlDelete +
                                '" onclick="return confirm(\'Apakah anda yakin? \')" class="btn btn-danger text-white btn-delete">Hapus</a></div>';
                        }
                    },
                ],
                columnDefs: [{
                    orderable: false,
                    searchable: false,
                    targets: 6
                }],
            });

            dt_init.delegate('a.btn-delete', 'click', function(e) {
                e.preventDefault();

                const url = $(this).attr('href');

                $.ajax({
                    method: 'DELETE',
                    headers: {
                        'Accept': 'application/json'
                    },
                    url: url,
                    success: function(response) {
                        alert(response.message);
                        window.location.href = "{{ route('karyawan.index') }}";
                    }
                });
            });
        });
    </script>
@endpush